from datetime import UTC, datetime
from pathlib import Path
import os

from dotenv import load_dotenv
from pymongo import MongoClient


ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / "backend" / ".env")

client = MongoClient(os.getenv("MONGO_URI", "mongodb://127.0.0.1:27017/"))
db = client[os.getenv("DB_NAME", "macro_finder")]
menu_items = db["menu_items"]


def build_item(
    *,
    restaurant_id,
    restaurant_name,
    item_name,
    category,
    price_cad,
    calories,
    protein_g,
    carbs_g,
    fat_g,
    sodium_mg,
    sugar_g,
    portion="1 item",
    description="",
    source_url="",
    price_source_url="",
):
    unique_key = f"{restaurant_id}|{item_name}|{portion}".lower()
    return {
        "restaurant_id": restaurant_id,
        "restaurant_name": restaurant_name,
        "item_name": item_name,
        "category": category,
        "portion": portion,
        "unique_key": unique_key,
        "price_cad": price_cad,
        "source_url": source_url,
        "price_source_url": price_source_url,
        "scraped_at": datetime.now(UTC).isoformat(),
        "description": description,
        "nutrition_invalid": False,
        "macros": {
            "calories": calories,
            "protein_g": protein_g,
            "carbs_g": carbs_g,
            "fat_g": fat_g,
            "sodium_mg": sodium_mg,
            "sugar_g": sugar_g,
        },
    }


CHOPPED_LEAF_NUTRITION = "https://choppedleaf.ca/wp-content/uploads/Nutritions.pdf"
CHOPPED_LEAF_PRICE = (
    "https://www.ubereats.com/ca/store/chopped-leaf-sunridge-superstore/rWBN8YnHXVKcAV1mLX-ABg"
)

BOOSTER_NUTRITION = (
    "https://cdn.shopify.com/s/files/1/0673/9371/6482/files/Nutrition-Guide-Jan2026.pdf"
)
BOOSTER_PRICE = (
    "https://www.ubereats.com/ca/store/booster-juice-300-5-ave-sw/r-J-UvuFXFi0EvlwBmCg5w"
)


ITEMS = [
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Bold Buffalo Bowl",
        category="bowl",
        price_cad=14.15,
        calories=400,
        protein_g=9,
        carbs_g=18,
        fat_g=33,
        sodium_mg=1260,
        sugar_g=5,
        description="Buffalo-style rice bowl with crunchy vegetables and ranch heat.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Bangkok Bowl",
        category="bowl",
        price_cad=14.15,
        calories=390,
        protein_g=12,
        carbs_g=45,
        fat_g=20,
        sodium_mg=500,
        sugar_g=12,
        description="Peanut-forward bowl with vegetables, grains, and a bigger carb base.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Caesar Bowl",
        category="bowl",
        price_cad=14.15,
        calories=370,
        protein_g=9,
        carbs_g=13,
        fat_g=32,
        sodium_mg=720,
        sugar_g=2,
        description="A heavier Caesar-style bowl with rice and crisp romaine.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Cobb Bowl",
        category="bowl",
        price_cad=14.15,
        calories=500,
        protein_g=16,
        carbs_g=16,
        fat_g=43,
        sodium_mg=680,
        sugar_g=5,
        description="Egg, bacon, cheddar, and avocado make this the richer high-protein bowl.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Harvest Bowl",
        category="bowl",
        price_cad=14.15,
        calories=400,
        protein_g=7,
        carbs_g=25,
        fat_g=32,
        sodium_mg=610,
        sugar_g=10,
        description="A sweeter grain bowl with cranberries, pecans, and chickpeas.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Mediterranean Bowl",
        category="bowl",
        price_cad=14.15,
        calories=350,
        protein_g=7,
        carbs_g=16,
        fat_g=29,
        sodium_mg=580,
        sugar_g=4,
        description="Greek-style bowl with feta, cucumber, olives, and grains.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Signature Bowl",
        category="bowl",
        price_cad=14.15,
        calories=390,
        protein_g=7,
        carbs_g=28,
        fat_g=29,
        sodium_mg=480,
        sugar_g=13,
        description="Signature greens bowl with rice, cranberries, pecans, and balsamic.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Southwest Bowl",
        category="bowl",
        price_cad=14.15,
        calories=370,
        protein_g=9,
        carbs_g=27,
        fat_g=26,
        sodium_mg=340,
        sugar_g=7,
        description="Southwest-style bowl with bean corn salsa and chipotle notes.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Sunshine Bowl",
        category="bowl",
        price_cad=14.15,
        calories=350,
        protein_g=7,
        carbs_g=15,
        fat_g=31,
        sodium_mg=500,
        sugar_g=5,
        description="Lighter bowl with apples, mozzarella, cucumber, and avocado.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Santa Fe Bowl",
        category="bowl",
        price_cad=14.15,
        calories=320,
        protein_g=10,
        carbs_g=34,
        fat_g=18,
        sodium_mg=690,
        sugar_g=8,
        description="Popular Calgary bowl with bean corn salsa, cheddar, and avocado.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Goddess Bowl",
        category="bowl",
        price_cad=14.15,
        calories=470,
        protein_g=14,
        carbs_g=29,
        fat_g=35,
        sodium_mg=650,
        sugar_g=8,
        description="Sweet potato and chickpea bowl built around the chain’s goddess dressing.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Caesar Wrap",
        category="wrap",
        price_cad=11.79,
        calories=730,
        protein_g=31,
        carbs_g=60,
        fat_g=43,
        sodium_mg=1930,
        sugar_g=6,
        description="High-protein Caesar wrap with bacon bits, parmesan, and tortilla.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Santa Fe Wrap",
        category="wrap",
        price_cad=11.79,
        calories=820,
        protein_g=31,
        carbs_g=59,
        fat_g=53,
        sodium_mg=1360,
        sugar_g=5,
        description="Bean corn salsa wrap with cheddar, sour cream, and avocado.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Mediterranean Wrap",
        category="wrap",
        price_cad=11.79,
        calories=850,
        protein_g=35,
        carbs_g=73,
        fat_g=49,
        sodium_mg=1480,
        sugar_g=16,
        description="Mediterranean wrap with feta, olives, cucumber, and tzatziki.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Harvest Wrap",
        category="wrap",
        price_cad=11.79,
        calories=740,
        protein_g=29,
        carbs_g=60,
        fat_g=45,
        sodium_mg=1500,
        sugar_g=7,
        description="Pecan, chickpea, cranberry wrap that still lands as a gym lunch.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="chopped_leaf_ca",
        restaurant_name="The Chopped Leaf (Canada)",
        item_name="Bangkok Wrap",
        category="wrap",
        price_cad=11.79,
        calories=710,
        protein_g=40,
        carbs_g=56,
        fat_g=38,
        sodium_mg=1240,
        sugar_g=5,
        description="Peanut and crunch-heavy wrap with the best protein of the group.",
        source_url=CHOPPED_LEAF_NUTRITION,
        price_source_url=CHOPPED_LEAF_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Strawberry Sunshine",
        category="smoothie",
        price_cad=9.55,
        calories=410,
        protein_g=4,
        carbs_g=97,
        fat_g=1,
        sodium_mg=50,
        sugar_g=76,
        portion="710 mL",
        description="Classic strawberry smoothie and one of the chain’s staple calorie sources.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Mango Hurricane",
        category="smoothie",
        price_cad=9.55,
        calories=360,
        protein_g=3,
        carbs_g=84,
        fat_g=1,
        sodium_mg=50,
        sugar_g=73,
        portion="710 mL",
        description="Fruit-forward smoothie with moderate calories and low fat.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Very Berry",
        category="smoothie",
        price_cad=9.55,
        calories=390,
        protein_g=3,
        carbs_g=89,
        fat_g=2,
        sodium_mg=65,
        sugar_g=75,
        portion="710 mL",
        description="Berry-heavy smoothie with a straightforward macro profile.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Tropical Tornado",
        category="smoothie",
        price_cad=9.55,
        calories=440,
        protein_g=4,
        carbs_g=104,
        fat_g=1,
        sodium_mg=35,
        sugar_g=83,
        portion="710 mL",
        description="High-carb tropical smoothie that works better as a bulk option than a cut option.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Spinach Is In It",
        category="smoothie",
        price_cad=10.61,
        calories=310,
        protein_g=3,
        carbs_g=72,
        fat_g=4,
        sodium_mg=30,
        sugar_g=65,
        portion="710 mL",
        description="One of the greener smoothie options with lower calories than the classics.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Tropi-Kale",
        category="smoothie",
        price_cad=10.61,
        calories=310,
        protein_g=3,
        carbs_g=75,
        fat_g=2,
        sodium_mg=20,
        sugar_g=59,
        portion="710 mL",
        description="Greens smoothie that looks healthier on paper and on the homepage.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Wildberry Rush",
        category="smoothie",
        price_cad=9.55,
        calories=210,
        protein_g=1,
        carbs_g=51,
        fat_g=1,
        sodium_mg=60,
        sugar_g=39,
        portion="710 mL",
        description="Lower-calorie smoothie option for users filtering by lighter picks.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Ripped Berry",
        category="smoothie",
        price_cad=10.49,
        calories=470,
        protein_g=29,
        carbs_g=84,
        fat_g=4,
        sodium_mg=290,
        sugar_g=64,
        portion="710 mL",
        description="The obvious gymmer smoothie: high protein, still sugary, but useful for compare.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Strawberry Storm",
        category="smoothie",
        price_cad=10.49,
        calories=390,
        protein_g=23,
        carbs_g=70,
        fat_g=3,
        sodium_mg=210,
        sugar_g=51,
        portion="710 mL",
        description="High-protein strawberry smoothie with lower calories than Ripped Berry.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Nuttin' Better",
        category="smoothie",
        price_cad=10.49,
        calories=770,
        protein_g=39,
        carbs_g=100,
        fat_g=27,
        sodium_mg=400,
        sugar_g=66,
        portion="710 mL",
        description="Calorie-dense gym bulk smoothie with the highest protein in the Booster set.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="High Impact Açai",
        category="bowl",
        price_cad=10.96,
        calories=630,
        protein_g=28,
        carbs_g=119,
        fat_g=7,
        sodium_mg=290,
        sugar_g=92,
        portion="710 mL",
        description="Açaí-heavy superfood smoothie with a stronger protein count.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Mind Over Matcha",
        category="smoothie",
        price_cad=10.96,
        calories=430,
        protein_g=26,
        carbs_g=73,
        fat_g=7,
        sodium_mg=330,
        sugar_g=51,
        portion="710 mL",
        description="Matcha protein smoothie that fits the health-focused angle better than dessert drinks.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="The Busy Bee Açai Bowl",
        category="bowl",
        price_cad=15.33,
        calories=630,
        protein_g=12,
        carbs_g=97,
        fat_g=22,
        sodium_mg=50,
        sugar_g=56,
        description="Açaí bowl for the homepage bowl category and lighter café feel.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="The Hippie Açai Bowl",
        category="bowl",
        price_cad=15.33,
        calories=560,
        protein_g=11,
        carbs_g=85,
        fat_g=20,
        sodium_mg=45,
        sugar_g=46,
        description="Lower-calorie açaí bowl that still looks like a healthy café item.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Chipotle Chicken Wrap",
        category="wrap",
        price_cad=9.78,
        calories=420,
        protein_g=31,
        carbs_g=39,
        fat_g=14,
        sodium_mg=1020,
        sugar_g=5,
        description="One of the more practical Booster food items for a high-protein quick meal.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
    build_item(
        restaurant_id="booster_juice_ca",
        restaurant_name="Booster Juice (Canada)",
        item_name="Guacamole Black Bean Wrap",
        category="wrap",
        price_cad=9.78,
        calories=350,
        protein_g=14,
        carbs_g=48,
        fat_g=12,
        sodium_mg=910,
        sugar_g=4,
        description="Plant-based wrap option for users who want a more obviously healthy lunch.",
        source_url=BOOSTER_NUTRITION,
        price_source_url=BOOSTER_PRICE,
    ),
]


inserted = 0
updated = 0

for item in ITEMS:
    result = menu_items.update_one(
        {"unique_key": item["unique_key"]},
        {"$set": item},
        upsert=True,
    )
    if result.upserted_id:
        inserted += 1
    elif result.modified_count:
        updated += 1

print(
    {
        "restaurants_seeded": len({item["restaurant_id"] for item in ITEMS}),
        "items": len(ITEMS),
        "inserted": inserted,
        "updated": updated,
    }
)
